### ISSUE TITLE
No Gendered Anaphora Resolution dataset included

### ISSUE THREAD

**Issue by eecrazy** [decompositional-semantics-initiative/DNC#1]
I find no Gendered Anaphora Resolution dataset included in this release.

**Comment by eecrazy** [comment]
Sorry, I find that Gendered Anaphora Resolution only has a test set.

**Comment by azpoliak** [comment]
Thanks for raising this issue. We only have test data for Gendered Anaphora Resolution. In the test set folder we called this file [`recast_winogender_data.json`](https://github.com/decompositional-semantics-initiative/DNC/blob/master/test/recast_winogender_data.json).

No need to apologize, we should add this as a note to the README.md
